data_params:
  img_folder: "media_oilpaint"
  num_clusters: 10
  img_size: 64
  batch_size: 128

model_params:
  num_colors: 3
  dense_size: [1024, 1024, 1024, 1024, 1024]

training_params:
  weight_decay: 0
  lr: 0.0001
