data_params:
  database: "C:/Users/Dalton/Google\ Drive/cs294-164/Huereka/bam.sqlite"
  img_size: 128
  crop_pad_px: 32
  batch_size: 4
  style: 'watercolor'
  num_clusters: 10

model_params:
  num_colors: 1
  channels: [8, 16, 32, 64, 128]
  dense: [1024, 1024]
  size: [3, 3]
  stride: [1, 1]
  pool_size: [2, 2]
  pool_strides: [2, 2]

training_params:
  weight_decay: 0.01
  learning_rate: [1e-3, 1e-4, 1e-5]
  steps: [5000, 5000, 5000]