data_params:
  img_folder: "C:/Users/Dalton/Google\ Drive/cs294-164/code/ml/media_oilpaint"
  img_size: 64
  crop_pad_px: 32
  batch_size: 8
  num_clusters: 7

model_params:
  num_colors: 3
  channels: [8, 16, 32, 64, 128]
  dense: [1024, 1024]
  size: [3, 3]
  stride: [1, 1]
  pool_size: [2, 2]
  pool_strides: [2, 2]

training_params:
  weight_decay: 1e-5
  lr: [1e-3, 1e-4, 1e-5]
  steps: [5000, 5000, 5000]